apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zndr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zndr
    app.kubernetes.io/part-of: byoc-app-ilac
  name: zndr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: zndr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: zndr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ukls-tenant/byoc-app-ilac/zndr@sha256:49c089da281bbae8e124531db6a052854a25f6a16e4eca9d74fb88f3c40be367
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
