apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: zndr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zndr
    app.kubernetes.io/part-of: byoc-app-ilac
  name: zndr1and
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: zndr
    weight: null
status: {}
